# Generated by Django 3.2.9 on 2022-01-03 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_Store', '0004_auto_20211220_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='شماره ی سفارش ')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی ')),
                ('phone', models.CharField(max_length=15, verbose_name='همراه ')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل ')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='آدرس اول ')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='آدرس دوم ')),
                ('country', models.CharField(max_length=50, verbose_name='کشور ')),
                ('state', models.CharField(max_length=50, verbose_name='دولت ')),
                ('city', models.CharField(max_length=50, verbose_name=' شهر ')),
                ('order_note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت سفارش ')),
                ('order_total', models.FloatField(verbose_name='جمع سفارش')),
                ('tax', models.FloatField(verbose_name='مالیات ')),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10, verbose_name='وضعیت محصول ')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='آی پی کاربر ')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='سفارش داده شده است  ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت ')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='آیدی پرداخت ')),
                ('payment_method', models.CharField(max_length=100, verbose_name='روش پرداخت ')),
                ('amount_paid', models.CharField(max_length=100, verbose_name='مبلغ پرداخت شده ')),
                ('status', models.CharField(max_length=100, verbose_name='وضعیت پرداخت ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوز پرداخت کننده ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ محصول ')),
                ('size', models.CharField(max_length=50, verbose_name='سایز محصول ')),
                ('quantity', models.IntegerField(verbose_name='تعداد محصول ')),
                ('product_price', models.FloatField(verbose_name='قیمت محصول ')),
                ('ordered', models.BooleanField(default=False, verbose_name='سفارش داده شده ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_Orders.order', verbose_name='سفارش ')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_Orders.payment', verbose_name='نوع پرداخت ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_Store.product', verbose_name='محصول سفارش داده ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوز سفارش دهنده ')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_Store.variation', verbose_name='تنوع محصول ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_Orders.payment', verbose_name='نوع پرداخت '),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='یوز سفارش دهنده '),
        ),
    ]
