# Generated by Django 3.2.9 on 2022-01-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'بخش سفارش ها  '},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'سفارش محصول', 'verbose_name_plural': 'بخش سفارش محصولات '},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'بخش پرداخت ها '},
        ),
    ]
