# Generated by Django 3.2.9 on 2022-01-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Orders', '0002_auto_20220110_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.IntegerField(verbose_name='قیمت محصول '),
        ),
    ]
