# Generated by Django 3.2.9 on 2021-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=55, unique=True, verbose_name='دسته بندی کلی ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name=' آدرس اسلاگ ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات ')),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/category', verbose_name='عکس دسته بندی ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی کلی',
            },
        ),
    ]
