# Generated by Django 3.2.9 on 2021-12-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='توضیحات '),
        ),
    ]
