# Generated by Django 3.2.9 on 2021-12-11 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_Home', '0002_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='نام محصول ')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس اسلاگ ')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات محصول ')),
                ('price', models.IntegerField(verbose_name='قیمت محصول ')),
                ('images', models.ImageField(upload_to='photos/products', verbose_name='تصویر محصول ')),
                ('stock', models.IntegerField(verbose_name=' انبار ')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود بودن کالا')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('modified_data', models.DateTimeField(auto_now=True, verbose_name=' تاریخ ویرایش ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_Home.category', verbose_name='دسته بندی محصول ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
