# Generated by Django 3.2.9 on 2021-12-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name=' تعداد کالا در انبار '),
        ),
    ]
