# Generated by Django 3.2.9 on 2021-12-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Store', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100, verbose_name='دسته بندی (تنوع) بر اساس رنگ - سایز')),
                ('variation_value', models.CharField(max_length=100, verbose_name='نوع تنوع محصول ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('created_data', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_Store.product', verbose_name='کدام محصول (تنوع) دارد')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'نوع محصول (براساس :رنگ - سایز ) ',
            },
        ),
    ]
