# Generated by Django 3.2.9 on 2021-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Store', '0003_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'نوع', 'verbose_name_plural': 'نوع محصول (براساس : رنگ - سایز ) '},
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100, verbose_name='دسته بندی (نوع) بر اساس رنگ - سایز'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100, verbose_name='نوع تنوع محصول(مثال : color-آبی) '),
        ),
    ]
