# Generated by Django 3.2.9 on 2021-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=50, verbose_name='فامیل ')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری ')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='ایمیل ')),
                ('phone_number', models.CharField(max_length=50, verbose_name='همراه ')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت ')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='آخرین ورود ')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارکنان سایت ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است ')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='ادمین کل ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
