# Generated by Django 3.2.9 on 2021-12-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
