# Generated by Django 3.2.9 on 2021-12-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_Store', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=255, verbose_name='آیدی سبد خرید ')),
                ('data_added', models.DateField(auto_now_add=True, verbose_name='تاریخ افزودن ')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال ')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_Cart.cart', verbose_name='سبد خرید ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_Store.product', verbose_name='محصول ')),
            ],
        ),
    ]
