# Generated by Django 3.2.9 on 2021-12-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد', 'verbose_name_plural': 'سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'محصول به سبد خرید ', 'verbose_name_plural': 'محصولات سبد خرید'},
        ),
    ]
