# Generated by Django 3.2.9 on 2021-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Store', '0004_auto_20211220_1117'),
        ('eshop_Cart', '0002_auto_20211219_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='eshop_Store.Variation', verbose_name='تنوع محصول با کدام آیتم'),
        ),
    ]
